services:
  trunk_recorder:
    image: thegreatcodeholio/icad_tr_uploader:RC5.0
    container_name: trunk_recorder
    restart: always
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - ./tr_config:/app/tr_config
      - ./tr_audio:/app/tr_audio
      - ./tr_logs:/app/tr_logs
