services:
  trunk_recorder:
    image: thegreatcodeholio/trunk-recorder-mqtt:5.0_organized
    container_name: trunk_recorder
    restart: always
    privileged: true
    stdin_open: true
    tty: true
    shm_size: '4gb'
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - ./config.json:/app/config.json
      - ./tr_config:/app/tr_config
      - ./tr_audio:/app/tr_audio
      - ./tr_logs:/app/tr_logs