FROM ubuntu:22.04

# Install additional dependencies
RUN apt update && apt upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential  \
    ca-certificates \
    cmake  \
    curl \
    docker.io \
    fdkaac \
    ffmpeg \
    git  \
    gnuradio-dev  \
    gr-funcube \
    gr-iqbal \
    libairspy-dev  \
    libairspyhf-dev  \
    libairspyhf1 \
    libbladerf-dev  \
    libboost-all-dev  \
    libboost-chrono1.74.0 \
    libboost-log1.74.0  \
    libcurl4-openssl-dev  \
    libfreesrp-dev  \
    libfreesrp0 \
    libgmp-dev  \
    libgnuradio-analog3.10.1 \
    libgnuradio-digital3.10.1 \
    libgnuradio-filter3.10.1 \
    libgnuradio-network3.10.1  \
    libgnuradio-uhd3.10.1 \
    libhackrf-dev  \
    libmirisdr-dev  \
    liborc-0.4-dev  \
    libpaho-mqtt-dev \
    libpaho-mqttpp-dev \
    libpthread-stubs0-dev  \
    libsndfile1-dev  \
    libsoapysdr-dev  \
    libsoapysdr0.8 \
    libssl-dev  \
    libuhd-dev  \
    libusb-1.0-0-dev  \
    libusb-dev  \
    libxtrx-dev  \
    libxtrx0 \
    pkg-config  \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-six \
    python3.11  \
    python3.11-distutils \
    python3.11-venv \
    rsync \
    rtl-sdr \
    soapysdr0.8-module-all \
    sox \
    wget \
    && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Fix the error message level for SmartNet

RUN sed -i 's/log_level = debug/log_level = info/g' /etc/gnuradio/conf.d/gnuradio-runtime.conf

# Compile librtlsdr-dev 2.0 for SDR-Blog v4 support and other updates
# Ubuntu 22.04 LTS has librtlsdr 0.6.0
RUN cd /tmp && \
  git clone https://github.com/steve-m/librtlsdr.git && \
  cd librtlsdr && \
  mkdir build && \
  cd build && \
  cmake .. && \
  make -j$(nproc) && \
  make install && \
  ldconfig && \
  cd /tmp && \
  rm -rf librtlsdr

# Compile gr-osmosdr ourselves using a fork with various patches included
RUN cd /tmp && \
  git clone https://github.com/racerxdl/gr-osmosdr.git && \
  cd gr-osmosdr && \
  mkdir build && \
  cd build && \
  cmake -DENABLE_NONFREE=TRUE .. && \
  make -j$(nproc) && \
  make install && \
  ldconfig && \
  cd /tmp && \
  rm -rf gr-osmosdr

RUN cd / &&  \
    mkdir src &&  \
    cd src && \
    git clone -b rc/v5.0 https://github.com/robotastic/trunk-recorder.git && \
    git clone -b test/autobuild https://github.com/taclane/trunk-recorder-mqtt-status.git /src/trunk-recorder/user-plugins && \
    cd trunk-recorder && \
    mkdir build && \
    cd build && \
    cmake ../ && \
    make -j$(nproc) && \
    make install


# Clone and build Trunk Recorder MQTT Status Plugin
#RUN git clone https://github.com/taclane/trunk-recorder-mqtt-status.git \
#    && cd trunk-recorder-mqtt-status \
#    && mkdir build && cd build \
#    && cmake ../ \
#    && make install \
#    && cd ../.. && rm -rf trunk-recorder-mqtt-status

# Upgrade PIP
RUN pip3 install --upgrade pip

# Set the working directory in the container
WORKDIR /app

# Install iCAD TR Uploader
RUN git clone https://github.com/TheGreatCodeholio/icad_tr_uploader.git && \
    rm -rf icad_tr_uploader/etc && \
    cd icad_tr_uploader &&  \
    pip3 install -r requirements.txt

# GNURadio requires a place to store some files, can only be set via $HOME env var.
ENV HOME=/tmp

CMD trunk-recorder --config=/app/tr_config/tr_config.json